name: Lean Action CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail" 
      - name: Build docs
        run: lake build MathematicalLogic:docs
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .lake/build/doc/
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
